<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\BadrHospital.Domain\BadrHospital.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Services\Auth\Commands\LogIn\" />
		<Folder Include="Services\Auth\Commands\ForgetPassword\" />
		<Folder Include="Services\Auth\Commands\ResetPassword\" />
		<Folder Include="Services\Auth\DTOs\" />
		<Folder Include="Services\Auth\Queries\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
	  <PackageReference Include="MediatR" Version="14.2.0" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
	</ItemGroup>

	<ItemGroup>
	  <FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

</Project>
